### ISSUE TITLE
How about authentication, because json result from sql, no need model?

### ISSUE THREAD

**Issue by meninjanho4788** [Microsoft/sql-server-samples#170]
How can i use authentication for this case

**Comment by shiitake** [comment]
Can you clarify your question please. 

Is there a particular sample in particular you're looking at?

**Comment by JocaPC** [comment]
I will assume that you are talking about the samples in feature/json folder where we are generating JSON in sql. Generating JSON in SQL and access control to your C# method (i.e. controller actions) are completely independent. You can use existing auth mechanism to control what user can execute some action. If your can invoke Product/Edit, then you will just execute underlying sql and generate JSON response.

**Comment by jovanpop-msft** [comment]
I'm closing this question because there are no additional responses. My suggestion would be to take a look at [ASP.NET Core security](https://docs.microsoft.com/en-us/aspnet/core/security/) where it is described how to implement authentication. Authentication and security is independent of model unless if you are relying on SQL Server security model where you would pass identity to database.
