### ISSUE TITLE
Unable to load adalsql.dll

### ISSUE THREAD

**Issue by jdthorpe** [Microsoft/sql-server-samples#265]
I have VS2015 with SSDT installed along with the [SqlServer](https://www.powershellgallery.com/packages/SqlServer/21.0.17152) PowerShell module, and yet If I try to execute a query against an Azure SQL DW like so:

    invoke-sqlcmd  -Query "Select top 5 * from customer"  -ConnectionString "Server=tcp:my.database.windows.net,1433;Database=Customer;  Authentication=Active Directory Integrated; Encrypt=True; "

I get the following error:

	invoke-sqlcmd : Unable to load adalsql.dll (Authentication=ActiveDirectoryIntegrated). Error code: 0x2. For more information, see
	http://go.microsoft.com/fwlink/?LinkID=513072
	At line:1 char:1
	+ invoke-sqlcmd  -Query "Select top 5 * from vwOffer"  -ConnectionStrin ...
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
		+ FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand

	invoke-sqlcmd :
	At line:1 char:1
	+ invoke-sqlcmd  -Query "Select top 5 * from vwOffer"  -ConnectionStrin ...
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserException
		+ FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Management.PowerShell.GetScriptComman

If I try and install [adalsql.dll](http://go.microsoft.com/fwlink/?LinkID=513072) directly, I get a message stating that `A higher version already exists` and I can see the both versions of the dll can be found here:

     C:\Windows\SysWOW64\adalsql.dll
     C:\Windows\System32\adalsql.dll

and yet, invoke-sqlcmd cant find it.   Any idea how to either (A) register the existing dll so invoke-sqlcmd can find it or (B) uninstall it so that it can be re-installed?

**Comment by jdthorpe** [comment]
Apparently the 64 bit version of `adalsql.dll` that comes with SSDT is buggy.  I uninstalled Active Directory Authentication Library via `settings` > `Add or Remove Programs`, reinstalled [adalsql.dll](http://go.microsoft.com/fwlink/?LinkID=513072) directly, and apparently everything is now hunky-dory.

**Comment by Quyentl** [comment]
Create new folder with Path HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSADALSQL
Add new key (String Value) TargetDir with data  column C:\Windows\System32\adalsql.dll
This is the websites I read:
https://winterdom.com/2017/09/27/unable-to-locate-registry-entry-for-adalsql.
https://feedback.azure.com/forums/908035-sql-server/suggestions/32897377-unable-to-load-adalsql-dll

**Comment by tullo-x86** [comment]
# Summary

* Newer ADAL binary is named `adal.dll`.
* Older ADAL binary is named `adalsql.dll`.

* The 32-bit version is installed at `C:\Windows\SysWOW64\adal(sql).dll`
* The 64-bit version is installed at `C:\Windows\System32\adal(sql).dll`

Registry has entries for each bitness.

ADO.NET checks the registry first, but falls back to `C:\Windows\(bitness)\adalsql.dll` if registry key not present.

Because `adal.dll` **is not a file named `adalsql.dll`**, this fallback fails for new versions of ADAL (which are installed with VS 2019 and onward).

Instead of checking for the installed package by GUID (which is `{6BF11ECE-3CE8-4FBA-991A-1F55AA6BE5BF}`, for anyone wondering) — ADO.NET simply assumes the missing file means the library is not installed, and informs the user thusly — cue frustration when, after attempting to install ADAL from MS website, Windows informs user that a newer version of ADAL is installed.

# Solution

Add this to your Windows registry:

```reg
Windows Registry Editor Version 5.00

; Indicate to the system where the 64-bit version of the
; MSSQL Active Directory Authentication Library is installed
; so that .NET applications don't rely on their outdated,
; broken fallback of `C:\Windows\<bitness>\adalsql.dll`.
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSADALSQL]
"TargetDir"="C:\\Windows\\System32\\adal.dll"
```
