### ISSUE TITLE
Tabular Database for SQL/SSAS 2012

### ISSUE THREAD

**Issue by rushabh138** [Microsoft/sql-server-samples#301]
I am trying to setup AdventureWorks2012 database for Analysis project. The core concept of this project is to learn to design data model using tabular mode. 

I'm using SQL Server version 2012. Based on release note, tabular database is supported for SQL 2016 and later.

Can you guide me, which database should I use for SQL/SSAS 2012? I want to built tabular database from start. Please provide me link to download database for analysis service 2012.

Thanks for your response. 

Rushabh.

**Comment by theCameronK** [comment]
Same issue. My company uses the Adventure Works 2012 Tabular Model for a lot of training and sadly 2014 is too different. We can't find the .abf file of the Adventure Works 2012 to download on CodePlex anymore and we need it.

**Comment by Minewiskan** [comment]
@theCameronK @rushabh138 I'm glad you found the sample model so helpful. I created it, and it's always gratifying to hear it helped so many users. 
The completed AdventureWorks tabular model sample database for SQL AS 2012 was removed from downloads because there was a bug in the model.bim. 
You can still complete the original 2012 tabular model tutorial and have the same result as the completed sample: Tabular Modeling (Adventure Works Tutorial) https://technet.microsoft.com/en-us/library/hh231691(v=sql.110).aspx. In SSDT, when creating the project, make sure you select the 1100 compatibility level.
The AdventureWorksDW 2012 database is still available as a datasource at https://github.com/Microsoft/sql-server-samples/releases.

If you use the tutorial and a more recent version of SSDT to create your own model, you will not get the bug in the model.bim.

Keep in-mind, tabular models at the 1100 (2012) and 1103 (2014) are now deprecated. Beginning with SQL 2016, the model.bim is json instead of xml and offers significant improvements over 1100 and 1103 level models. Also, you cannot deploy 1100 and 1103 models to Azure Analysis Services.

Thanks you
