### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by birama** [Microsoft/sql-server-samples#357]
Hi , 
is there any french translation ?

**Comment by CubeSpark** [comment]
Birama? Do you mean French translation of the SQL language itself?  There is not.  SQL is fully English, unfortunately. Most programming languages are English, even Assembler and FORTRAN. There were no great French language code inventors, because the industry was invented by the US and British Military to defeat enemies or to optimize business processes.

**Comment by jodebrui** [comment]
The SQL Server samples repository is English only at this time.
