### ISSUE TITLE
Not playing well with EF6 Designer

### ISSUE THREAD

**Issue by julielerman** [Microsoft/sql-server-samples#57]
Some experiments have seemingly narrowed a problem down to this database. I tried the same with adventureworks in SQL Server 2016 and it's not a problem.

In VS2015 SP2 with *latest* SSDT tools (june 2016), SQL Server 2016 Developer Edition and SSMS for SQL Server 2016 installed.

Create new class library project.

Add new item: Entity Framework Data Model.

Select connection to World Wide Importers (not DW) on SQL Server 2016 instance.

Select all tables.

Go (which will install EF6 package and reverse engineer itables into classes).

It takes about 3 minutes. It should take about 10 seconds max.

Doing the same with AdventureWorks (not LT) is about 10 seconds. 
I did this a number of time and each time it takes a while.
Is there something particular about the database schema or special SS2016 features that might create this problem? I don't normally recommend building a model from an entire database but this also happens if I only select a handful of tables.
It seems specific to the database and will make it hard for people to use when using it to explore EF.

On the other hand, I know how Greg feels about EF so maybe it's intentional. JUST KIDDING! :)

**Comment by jodebrui** [comment]
Thanks for trying out this scenario.
I will work with the EF folks to understand the issue.

**Comment by julielerman** [comment]
@jodebrui happy to show you on skype in prep if you want. Something tells me they are busy busy with EF Core and EF6 Designer may be last thing they are interested in right now...

**Comment by jodebrui** [comment]
Thanks for the offer, but no need. I can reproduce on my end.

**Comment by Kevin-Farlee** [comment]
Can we further narrow it down to one or a set of tables?  If we can do that, we can start to zero in on what features in WWI are causing SSDT to be inefficient.

**Comment by jodebrui** [comment]
As it turns out, the issue is with new CE and the reverse engineering queries.
If you revert to legacy CE, import of the database is going to be snappy.
Just run the following statement in the database before importing:

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION=ON

I will follow up with the QO and EF teams to see what we can do to address this problem.


Thanks,
Jos

From: Jos de Bruijn
Sent: Friday, June 10, 2016 1:22 PM
To: 'Microsoft/sql-server-samples' <reply@reply.github.com>; Microsoft/sql-server-samples <sql-server-samples@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/sql-server-samples] Not playing well with EF6 Designer (#57)

Thanks for the offer, but no need. I can reproduce on my end.

**Comment by jodebrui** [comment]
Updating the following statistics fixes the issue for the Full version of the sample:
update statistics sys.syscolpars
update statistics sys.sysschobjs

Standard version is still being investigated.

**Comment by jodebrui** [comment]
The following stats updates fix the problem for the Standard version of the sample DB:
update statistics sys.syscolpars
update statistics sys.sysschobjs
update statistics sys.syssingleobjrefs
update statistics sys.sysiscols

I updated the database create scripts and uploaded new backups to the release page.
With these updates, reverse engineering in EF6 takes <10 seconds for me.

Thanks again for reporting this issue.
Let us know if there are any further concerns or you encounter any other issues.


Thanks,
Jos
