### ISSUE TITLE
How do I restore a AdventureWorksDW to an Azure SQL Instance

### ISSUE THREAD

**Issue by sdg002** [microsoft/sql-server-samples#817]
Hi All,

I am trying to complete the SSAS tutorial on the Microsoft site. This tutorial references the AdventureWorkdsDW database. Please help me install the AdventureWorksDW on Azure SQL.

- The .BAK files are not supported on Azure 
- I could not find the BACPAC files for AdventureWorks any where.
- I tried the CSV approach, but the SQL script has commands which are not compatible with Azure SQL.

Thank you

**Comment by erapade** [comment]
Agree. Having the same problem for the Contoso sample db. 

The AdventureWorks OLTP database exists as an sample when creating a database in Azure, but the AdventureWorksDW (OLAP) does not. Just to make it clear for others

**Comment by pmasl** [comment]
See https://github.com/microsoft/sql-server-samples/tree/master/samples/databases/adventure-works#to-install-adventureworksdw

**Comment by erapade** [comment]
@pmasl I can see this is correctly closed since you referred to how to install the OLAP version.
A better solution though would have been to support all the Microsoft provided template databases already from the Azure portal, like AdventureWorks, WorldWideImporters, and Contosso. All in both OLAP and OLTP formats.

Reason for this. There's many users that needs access to these databases and that have no intention to learn T-SQL or SQL server administration. Having this already in the Azure portal would make it much more easier for these users
